apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-server
spec:
 replicas: 1
 selector:
   matchLabels:
     app: api-server
 template:
   metadata:
     labels:
       app: api-server
   spec:
     containers:
     - name: api-server
       image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
       command: ["python"]
       args: ["dev_init_db.py"]
       ports:
       - containerPort: 8000
       env:
       - name: DATABASE_URL
         valueFrom:
           secretKeyRef:
             name: db-credentials
             key: database-url
       - name: KUBERNETES_NAMESPACE
         valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
       - name: POD_IP
         valueFrom:
           fieldRef:
             fieldPath: status.podIP
       - name: NODE_NAME
         valueFrom:
           fieldRef:
             fieldPath: spec.nodeName
       - name: HOSTNAME
         valueFrom:
           fieldRef:
             fieldPath: metadata.name
       resources:
         {{- toYaml .Values.resources | nindent 10 }}