image:
  repository: postgres
  tag: "16"

replication:
  enabled: true
  replicas: 1
  
persistence:
  size: 1Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"