image:
  repository: sejokim/api-server
  tag: latest

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  host: "api.local"

service:
  type: ClusterIP
  port: 8000